#!/usr/bin/python3

# LICENSE : http://www.apache.org/licenses/LICENSE-2.0 
# (c) 2025 frankb 

import gdb 
import math 
import os.path 
import sys 
from datetime import datetime

sys.path.append('.')    

from struct2json import struct2json 

infile = "genJson.txt"

print('=================================')

s1 = ""

for line in open(infile,"r"):
    structname = line.rstrip()
    if len(structname) < 2:
        continue
    if structname.startswith("#"):
        continue
    print('=================================')
    print( 'genJson.py: Start with %s' % structname ); 
    s1 += struct2json( gdb.lookup_type( structname ) )

print( s1 )

fp_c = open( 'genJson.ino' , 'w+' )

fp_c.write( '/* This Files were generated by "genJson.ino" \r\n'
    ' * LICENSE : http://www.apache.org/licenses/LICENSE-2.0\r\n'
    ' * (c) 2025 frankb ' 
    ' * %s ' 
    ' */\r\n' %  ( datetime.today().isoformat() )
)

fp_c.write( s1 )
